#!/bin/bash

scheme1="https://"
scheme2="http://"

sed -i 's/google/yandex/g' input.txt # change everywhere

for LIST in $(cat input.txt); do
#        echo $LIST

 #   echo ${#LIST}
  #  echo ${LIST:0:8}
    LIST2=$LIST
    if [[ (${#LIST} -ge 7)  && ${LIST:0:7} == "http://" ]]
    then
        echo "Scheme: $scheme2" >>output.txt
        tem2=(${#LIST} - 7 - 1)
        LIST2=${LIST:7:tem2}
   #     sed -i 's!http://!' input.txt
       # echo $scheme1 >>output.txt
    fi

    if [[ (${#LIST} -ge 8)  && ${LIST:0:8} == "https://" ]]
    then
        echo "Scheme: $scheme1" >>output.txt
        tem2=(${#LIST} - 8 - 1)
        LIST2=${LIST:8:tem2}
    #    sed -i 's!https://!!' input.txt
       # echo $scheme1 >>output.txt
    fi

 #   echo $LIST2

    host1=""
    i=0
    for((; i < ${#LIST2}; i += 1)); do
        if [[ ${LIST2:i:1} == '/' || ${LIST2:i:1} == ':' || ${LIST2:i:1} == '\n' ]]
        then
            break
        fi
       # echo " " >> output.txt
       # echo $LIST[i] >>output.txt
    done
    echo "Host:" ${LIST2:0:i} >>output.txt
    tem2=(${#LIST2} - i - 1)
    tempor=${LIST2:i:tem2}
    #echo $tempor
    # now work with tempor

    tempor2=$tempor

    if [[ ${tempor:0:1} == ':' ]] 
    then

        i=1
        for((; i < ${#tempor}; i += 1)); do
            if [[ ${tempor:i:1} == '/' || ${tempor:i:1} == '\n' ]]
            then
                break
            fi
        done
        echo "Port:" ${tempor:1:i-1} >>output.txt
        tem2=(${#tempor} - i - 1)
        tempor2=${tempor:i:tem2}
    fi
   # echo $tempor2

    temp3=${tempor2:0:1}


    if [[ $temp3 == '/' ]] 
    then

        echo "Args:" >>output.txt   

        tem2=(${#tempor} - 1 - 1)
        tempor2=${tempor2:2:tem2}

        #echo $tempor2

        quant_keys=0
        for((i=0; i < ${#tempor2}; i += 1)); do
            if [[ ${tempor2:i:1} == '=' ]]
            then
                (( quant_keys += 1 )) 
            
            fi
        done

        #echo $quant_keys

        for((j=0; j < quant_keys; j += 1)); do

            i=0
            for((; i < ${#tempor2}; i += 1)); do
                if [[ ${tempor2:i:1} == '=' || ${tempor2:i:1} == '\n' ]]
                then
                    break
                fi
            done

            

            l=$i

            for((; i < ${#tempor2}; i += 1)); do
                if [[ ${tempor2:i:1} == '&' || ${tempor2:i:1} == '\n' ]]
                then
                    break
                fi
            done

            echo "  Key: ${tempor2:0:l}; Value: ${tempor2:l+1:i-1-l}" >>output.txt     

            tem2=(${#tempor} - i - 1)
            tempor2=${tempor2:i+1:tem2}
            
        done
    fi


    echo -e >>output.txt
done
#echo "asdfasdf" > output.txt
